"""The shapes a simple alpha takes.

Every one of these is the same three-step move that most working alphas make: take a raw
number, make it comparable over time, then make it comparable across stocks and strip
out what they all share. They are deliberately plain — this is the stage where the point
is *volume*, not cleverness. A hundred ordinary alphas over a hundred fields finds more
than one elaborate alpha over one.

``ts_backfill`` wraps every field because most data outside price and volume updates
quarterly or on an event, leaving gaps on most days. It does not count against the
platform's operator budget, so it is free to apply everywhere.

Patterns are kept here rather than generated by a model because they need to be correct
and cheap, not novel. The LLM's job is the part where novelty pays.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True, slots=True)
class Pattern:
    """One alpha shape with a field and a window left open."""

    name: str
    #: ``{field}`` and ``{window}`` are substituted; ``{group}`` when it groups.
    template: str
    #: What it is betting on, in the words a beginner needs.
    idea: str
    #: Operators used, so the Power Pool budget can be counted without parsing.
    operators: int
    grouped: bool = False

    def render(self, field: str, window: int, group: str = "industry") -> str:
        return self.template.format(field=field, window=window, group=group)

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "idea": self.idea,
            "operators": self.operators,
            "grouped": self.grouped,
            "example": self.render("assets", 252),
        }


PATTERNS: tuple[Pattern, ...] = (
    Pattern(
        "ts_zscore_neutral",
        "group_neutralize(ts_zscore(ts_backfill({field}, 120), {window}), {group})",
        "Is this number unusual for this company, after removing whatever the whole "
        "industry did? The workhorse shape.",
        operators=2,
        grouped=True,
    ),
    Pattern(
        "rank_zscore",
        "rank(ts_zscore(ts_backfill({field}, 120), {window}))",
        "The same idea, ranked across all stocks instead of neutralised by industry.",
        operators=2,
    ),
    Pattern(
        "ts_rank",
        "group_neutralize(ts_rank(ts_backfill({field}, 120), {window}), {group})",
        "Where does today's value sit inside its own recent range? Reacts to the "
        "direction of change rather than the level.",
        operators=2,
        grouped=True,
    ),
    Pattern(
        "change",
        "group_neutralize(ts_delta(ts_backfill({field}, 120), {window}), {group})",
        "How much has this number moved? Bets that the change itself carries the signal.",
        operators=2,
        grouped=True,
    ),
    Pattern(
        "reversal",
        "rank(-ts_delta(ts_backfill({field}, 120), {window}))",
        "The opposite bet: whatever moved most is due to move back.",
        operators=2,
    ),
    Pattern(
        "scaled_by_cap",
        "group_neutralize(ts_zscore(ts_backfill({field}, 120) / cap, {window}), {group})",
        "The number relative to company size, so a big firm's big number is not "
        "mistaken for a strong signal.",
        operators=3,
        grouped=True,
    ),
)

PATTERNS_BY_NAME = {p.name: p for p in PATTERNS}

#: Conventional windows: a quarter, half a year, a year, two years. Deliberately sparse
#: — searching 37 days alongside 21 is how a sweep fits noise instead of finding signal.
WINDOWS: tuple[int, ...] = (63, 126, 252, 504)

#: Grouping fields, in the order they are usually reached for.
GROUPS: tuple[str, ...] = ("industry", "subindustry", "sector", "market")


def catalogue() -> list[dict[str, Any]]:
    return [p.to_dict() for p in PATTERNS]
